#!/bin/bash

exit_with_error() {
    echo -e "\033[31m[ERROR]\033[0m $1"
}

rm dist/lb_lexer -rf
mkdir -p build
cd build
make
if [ $? -ne 0 ]; then
    exit_with_error "Failed to build."
    exit 1
fi
cp ./lb_lexer ../dist/
cd ../dist/
rm logs/* -rfd
export SPDLOG_LEVEL=TRACE
./lb_lexer ../src/main.cpp